Repository projectdiscovery/tlsx, pull requests merged in 2022-08, with the labels that each got.

#64 Adding openssl prototype via cgo bindings
  README.md
  assets/openssl.include
  cmd/tlsx/main.go
  go.mod
  go.sum
  internal/runner/runner.go
  pkg/output/stats/stats.go
  pkg/tlsx/auto/auto.go
  pkg/tlsx/clients/clients.go
  pkg/tlsx/openssl/common.go
  pkg/tlsx/openssl/no_openssl.go
  pkg/tlsx/openssl/openssl.go
  pkg/tlsx/tls/tls.go
  pkg/tlsx/tlsx.go
  pkg/tlsx/ztls/ztls.go
Labels: Status: In-Review, Type: Enhancement

#69 Adding initial support for tls version enum
  cmd/tlsx/main.go
  pkg/output/output.go
  pkg/tlsx/auto/auto.go
  pkg/tlsx/auto/util.go
  pkg/tlsx/clients/clients.go
  pkg/tlsx/openssl/no_openssl.go
  pkg/tlsx/openssl/openssl.go
  pkg/tlsx/tls/tls.go
  pkg/tlsx/tls/utils.go
  pkg/tlsx/tlsx.go
  pkg/tlsx/ztls/utils.go
  pkg/tlsx/ztls/ztls.go
Labels: Status: Review Needed, Type: Enhancement

#73 Fixed a potential panic with nil conn
  pkg/tlsx/auto/auto.go
  pkg/tlsx/tls/tls.go
  pkg/tlsx/ztls/ztls.go
Labels: Status: Review Needed
