Repository projectdiscovery/tlsx, pull requests merged in 2022-07, with the labels that each got.

#46 sni flag enhancement
  cmd/tlsx/main.go
  internal/runner/runner.go
  pkg/output/output.go
  pkg/tlsx/auto/auto.go
  pkg/tlsx/clients/clients.go
  pkg/tlsx/tls/tls.go
  pkg/tlsx/tlsx.go
  pkg/tlsx/ztls/ztls.go
Labels: Type: Enhancement

#47 Add --mis-match flag
  README.md
  cmd/tlsx/main.go
  go.mod
  go.sum
  internal/runner/banner.go
  pkg/output/output.go
  pkg/tlsx/clients/clients.go
  pkg/tlsx/tls/tls.go
  pkg/tlsx/ztls/ztls.go
Labels: Status: Revision Needed

#54 Added all-ciphers and retries flag for tls connection
  cmd/tlsx/main.go
  internal/runner/banner.go
  pkg/tlsx/clients/clients.go
  pkg/tlsx/tls/tls.go
  pkg/tlsx/tls/utils.go
  pkg/tlsx/tlsx.go
  pkg/tlsx/ztls/utils.go
  pkg/tlsx/ztls/ztls.go
Labels: Status: Review Needed

#57 ztls ja3
  cmd/tlsx/main.go
  internal/runner/banner.go
  pkg/output/output.go
  pkg/tlsx/clients/clients.go
  pkg/tlsx/ztls/ja3/ja3.go
  pkg/tlsx/ztls/ztls.go
Labels: Status: Review Needed, Type: Enhancement
