Repository projectdiscovery/tlsx, pull requests merged in 2023-01, with the labels that each got.

#144 adds os.exec openssl wrapper
  cmd/tlsx/main.go
  go.mod
  go.sum
  internal/runner/runner.go
  pkg/tlsx/auto/auto.go
  pkg/tlsx/clients/clients.go
  pkg/tlsx/clients/utils.go
  pkg/tlsx/openssl/common.go
  pkg/tlsx/openssl/no_openssl.go
  pkg/tlsx/openssl/openssl.go
  pkg/tlsx/openssl/openssl_exec.go
  pkg/tlsx/openssl/openssl_test.go
  pkg/tlsx/openssl/opensslpkg_test.go
  pkg/tlsx/openssl/options.go
  pkg/tlsx/openssl/utils.go
  pkg/tlsx/tls/tls.go
  pkg/tlsx/tlsx_test.go
Labels: Type: Enhancement

#154 Fixing zcrypto clone bug
  go.mod
  go.sum
Labels: Type: Bug

#155 Fixing high memory consumption
  pkg/tlsx/clients/clients.go
  pkg/tlsx/clients/utils.go
  pkg/tlsx/openssl/openssl.go
  pkg/tlsx/tls/tls.go
  pkg/tlsx/ztls/ztls.go
Labels: Type: Bug

#173 Adding support for healtcheck
  README.md
  cmd/tlsx/main.go
  go.mod
  internal/runner/healthcheck.go
  pkg/tlsx/clients/clients.go
  pkg/tlsx/openssl/common.go
  pkg/tlsx/openssl/openssl_exec.go
Labels: Type: Maintenance
